### ISSUE TITLE
Access to non-Pathfinder, STMS hosted, databases

### ISSUE THREAD

**Issue by ckayfish** [BCDevOps/issues-and-solutions#12]
As we begin using PaaS, and until data custody & stewardship better understood by myself, my team and everyone, I intend to use existing data repositories for application we move to this ecosystem. This will be continually reevaluated, but greatly simplifies our on-boarding.

To enable this, a quick list of things I'll need are:

1) To know that pathfinder allows TCP connections (_MSSQL_, Oracle, mySQL) from my containers out of it's ecosystem
2) To know that there is an OUTBOUND rule on your vLAN to allow this into at least Kamloops non-DMZ zones
3) What IP's/subnet (dont post these here) these connections will be coming from so I can create an INBOUND rule on my vLANS. *Preferably (but not expected) I can have a range or single IP assigned to my projects.

**Comment by cvarjao** [comment]
Cleaning old issues ...
The network and firewall object is documented in the FAQ:
https://pathfinder-faq-ocio-pathfinder-prod.pathfinder.gov.bc.ca/OCP/Network.html

**Comment by ckayfish** [comment]
Thanks for this, we just got this is set up recently. As I understand it we cannot get a dedicated IP address and we would need to allow all Pathfinder containers (defined by OCIO-PF-PROD-DMZ)  network access to our databases. This isn't ideal, but understandable.
