### ISSUE TITLE
How can we implement source IP restrictions in a framework-y way for OpenShift applications that only want to accept traffic from specific hosts (e.g. SiteMinder RP/LB)?

### ISSUE THREAD

**Issue by sheaphillips** [BCDevOps/issues-and-solutions#15]
We will have scenarios with applications that need to be "behind" non-OpenShift reverse proxies/load balancers and should only receive traffic from those hosts.

Is there an OpenShift-provide mechanism for achieving this, without baking something into the applications themselves?  While possible to do the latter, it would be better if we can leverage something provided by the platform.

**Comment by cvarjao** [comment]
@sheaphillips  , I am hoping this issue has been resolved with our most recent OpenShift (3.11) with [route whitelist](https://docs.openshift.com/container-platform/3.11/architecture/networking/routes.html#whitelist)
