### ISSUE TITLE
question about private image stream.

### ISSUE THREAD

**Issue by ll911** [BCDevOps/issues-and-solutions#16]
if vendor provides docker image from private stream (licensed product), what delivery method can be used in OpenShift?

**Comment by cvarjao-bcgov** [comment]
If i understand correctly, the DeploymentConfig can have a reference to external docker registries.
[](https://blog.openshift.com/remotely-push-pull-container-images-openshift/)
Doesn't that work?

**Comment by f-w** [comment]
docker pull to a localhost, then push to docker-registry.pathfinder.gov.bc.ca

**Comment by cvarjao** [comment]
cleaning up old issues ... @ll911, I think you have already resolved this problem.
You can use [image pull secret](https://docs.openshift.com/container-platform/3.11/dev_guide/managing_images.html#using-image-pull-secrets) to pull from private registries
